# Matrices (manual) Manipulation Using Numpy (Numerical Python) Library

# If you get errors, restart the kernel and rerun all cells.
# Do not run a single cell multiple times; run all cells in a sequence.
# Each problem is based on multiple & dependent cells.
# Running a single cell multiple times after previous manipulations may cause errors.

In [1]:
!pip install numpy
import numpy as np

In [3]:
# Row Matrix

In [4]:
row=np.array([   [1,2,3]    ])
row

array([[1, 2, 3]])

# Column Matrix

In [5]:
column=np.array([   [1],
                    [2],
                    [3]   ])
column

array([[1],
       [2],
       [3]])

# 2 dimensional Matrix, (2/2) & (3/3), Combine row & column.

In [6]:
M2_by_2=np.array([    [1,2],
                      [3,4]   ])

M3_by_3=np.array([    [1,2,3],
                      [4,5,6],
                      [7,8,9]   ])

print("\n2 by 2 Matrix \n",M2_by_2)
print("\n3 by 3 Matrix \n",M3_by_3)


2 by 2 Matrix 
 [[1 2]
 [3 4]]

3 by 3 Matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


# ADDITION

In [7]:
                                 # Using manual index-assignment, long but shows backend process

A=np.array([  [2,3],
              [1,6]  ])
B=np.array([  [1,8],
              [2,7]  ])
r=2
c=2
C=np.empty((r,c),  np.int64)


C[0][0]=A[0][0]+B[0][0]                      
C[0][1]=A[0][1]+B[0][1]
C[1][0]=A[1][0]+B[1][0]
C[1][1]=A[1][1]+B[1][1]

C

array([[ 3, 11],
       [ 3, 13]])

In [8]:
for x in range(r):                                      # Middle_one, through looping
    for y in range(c):
        C[x][y]=A[x][y]+B[x][y]
C

array([[ 3, 11],
       [ 3, 13]])

In [9]:
A+B                                                     # Easiet// built-in

array([[ 3, 11],
       [ 3, 13]])

# MULTIPLICATION

In [10]:
                                       # Using manual index-assignment, long but shows backend process     
A=np.array([  [2,3],
              [1,6]  ])
B=np.array([  [1,8],
              [2,7]  ])

C[0][0] = A[0][0]*B[0][0]  +  A[0][1]*B[1][0]                      
C[0][1] = A[0][0]*B[0][1]  +  A[0][1]*B[1][1]
C[1][0] = A[1][0]*B[0][0]  +  A[1][1]*B[1][0] 
C[1][1] = A[1][0]*B[0][1]  +  A[1][1]*B[1][1]
C

array([[ 8, 37],
       [13, 50]])

In [11]:
A*B                                    # This multiplication is not applicable to matrices 

array([[ 2, 24],
       [ 2, 42]])

# Transpose of a Matrix

In [12]:
                                        # Using manual index-assignment, long but shows backend process
Z=np.array([  [2,3,1],
              [4,5,9],
              [6,7,8] ])
r=3
c=3
T=np.empty((r,c),  dtype=int)

T[0][0]=Z[0][0]
T[0][1]=Z[1][0]
T[0][2]=Z[2][0]
T[1][0]=Z[0][1]
T[1][1]=Z[1][1]
T[1][2]=Z[2][1]
T[2][0]=Z[0][2]
T[2][1]=Z[1][2]
T[2][2]=Z[2][2]

print("Original_Matrix\n", Z)
print("\nTransposed_Matrix\n",T)

Original_Matrix
 [[2 3 1]
 [4 5 9]
 [6 7 8]]

Transposed_Matrix
 [[2 4 6]
 [3 5 7]
 [1 9 8]]


In [13]:
                                                   # Middle_one, through looping
r=3
c=3
T2=np.empty((r,c),  dtype=int)

for x in range(r):
    for y in range(c):
        T2[x][y]=Z[y][x]
T2

array([[2, 4, 6],
       [3, 5, 7],
       [1, 9, 8]])

In [14]:
print(Z.T)                 # easiest // built-in

[[2 4 6]
 [3 5 7]
 [1 9 8]]


# Determinant

In [16]:
D=np.array([  [2,4,6],
              [7,3,5],
              [1,9,8]  ])
Det=2*(3*8-5*9)-4*(7*8-5*1)+6*(7*9-3*1)

In [17]:
Det

114

# Adjoint of a Matrix

In [18]:
M=np.array([  [1, 1, 1],
               [-2,-1, 1],
                [3, 1,-5]   ])

a=((-1)**(0+0)) * ( (-5 * -1) - (1*1)  )
b=((-1)**(0+1)) * ( (-2 * -5) - (1*3)  )
c=((-1)**(0+2)) * ( (-2 *  1) - (-1*3) )
d=((-1)**(1+0)) * ( ( 1 * -5) - (1*1)  )
e=((-1)**(1+1)) * ( ( 1 * -5) - (1*3)  )
f=((-1)**(1+2)) * ( ( 1 *  1) - (1*3)  )
g=((-1)**(2+0)) * ( ( 1 *  1) - (-1*1) )
h=((-1)**(2+1)) * ( ( 1 *  1) - (1*-2) )
i=((-1)**(2+2)) * ( ( 1 * -1) - (1*-2) )

adj=np.empty((3,3),  dtype=int)

adj[0][0]=a
adj[0][1]=b
adj[0][2]=c
adj[1][0]=d
adj[1][1]=e
adj[1][2]=f
adj[2][0]=g
adj[2][1]=h
adj[2][2]=i

print("Found_co-factors of the matrix M  \n\n", adj)

Found_co-factors of the matrix M  

 [[ 4 -7  1]
 [ 6 -8  2]
 [ 2 -3  1]]


In [19]:
print("Transposed the Co_factors to shape adjoint of matrix M \n\n", adj.T)

Transposed the Co_factors to shape adjoint of matrix M 

 [[ 4  6  2]
 [-7 -8 -3]
 [ 1  2  1]]


# Inverse of a Matrix using Adjoint Method

In [24]:
I=np.array([  [1,0,2],
              [0,2,1],
             [1,-1,1]  ])    

# Inverse in adjoint method = adj/|I|
# where the determinant of the matrix should not be equal to zero

dt=1*( (2*1)-(-1*1) ) - 0*( (1*0)-(1*1) ) + 2*( (0*-1)-(1*2) )

dt

-1

In [25]:
j=((-1)**(0+0)) * ( (2*1) - (1*-1)  )
k=((-1)**(0+1)) * ( (0*1) - (1*1 )  )
l=((-1)**(0+2)) * ( (0*-1) - (2*1) )
m=((-1)**(1+0)) * ( (0*1) - (2*-1)  )
n=((-1)**(1+1)) * ( (1*1) - (2*1)  )
o=((-1)**(1+2)) * ( (1*-1) - (0*1)  )
p=((-1)**(2+0)) * ( (0*1) - (2*2) )
q=((-1)**(2+1)) * ( (1*1) - (0*2) )
r=((-1)**(2+2)) * ( (1*2) - (0*0) )

cf=np.empty((3,3),   dtype=float)

cf[0][0]=j
cf[0][1]=k
cf[0][2]=l
cf[1][0]=m
cf[1][1]=n
cf[1][2]=o
cf[2][0]=p
cf[2][1]=q
cf[2][2]=r

adj=cf.T
print("\nFound_co-factors of the matrix I  \n\n", cf)
print("\nTransposed the Co_factors to shape adjoint of matrix I \n\n",adj)


Found_co-factors of the matrix I  

 [[ 3.  1. -2.]
 [-2. -1.  1.]
 [-4. -1.  2.]]

Transposed the Co_factors to shape adjoint of matrix I 

 [[ 3. -2. -4.]
 [ 1. -1. -1.]
 [-2.  1.  2.]]


In [26]:
print("\nFinal inverse answer of the matrix I  \n\n", adj/dt)


Final inverse answer of the matrix I  

 [[-3.  2.  4.]
 [-1.  1.  1.]
 [ 2. -1. -2.]]


# System Of Equations¶
# Gauss elimination (forming Row Echelon Form)
# EQUATION
# 1x+1y+1z=6.
# 2x+3y+1z=10.
# 1x+2y+3z=13






# AX=B
# [1,1, 1] [x] [6]
# [2,3,1] [y] [10]
# [1,2,3] [z] [13]

In [43]:
A=np.array([    [1,1,1],
                [2,3,1],
                [1,2,3] ])
B=np.array([  [6],
             [10],
             [13]   ])
aug=np.concatenate((A,B),   axis=1)
aug

array([[ 1,  1,  1,  6],
       [ 2,  3,  1, 10],
       [ 1,  2,  3, 13]])

In [44]:
# >>  How to access the whole row and the whole column? 

#     first row = Matri[0]                 = R1.
#     2nd row = Matrix[1]                   = R2.
#     third row = Matrix[2]                 = R3.
#     first column = Matrix[ : , 0]         = C1.
#     2nd column = Matrix[ : , 1]           = C2.
#     third column = Matrix[ : , 2 ]        = C3.

In [45]:
aug[1]=aug[1]-2*aug[0]                         # >>  R2 = R2-2R1
aug

array([[ 1,  1,  1,  6],
       [ 0,  1, -1, -2],
       [ 1,  2,  3, 13]])

In [46]:
aug[2]=aug[2]-1*aug[0]                         # >>  R3 = R3-R1
aug

array([[ 1,  1,  1,  6],
       [ 0,  1, -1, -2],
       [ 0,  1,  2,  7]])

In [47]:
aug[2]=aug[2]-1*aug[1]                         # >>  R3 = R3-R2
aug

array([[ 1,  1,  1,  6],
       [ 0,  1, -1, -2],
       [ 0,  0,  3,  9]])

In [48]:
aug[2]=aug[2]/3                                # >>  R3 = R3/3.
print("\nProduced row echelon form !\n")
aug


Produced row echelon form !



array([[ 1,  1,  1,  6],
       [ 0,  1, -1, -2],
       [ 0,  0,  1,  3]])

# x=2 , y=1 , z=3 (Row echelon form values)
# Gauss-Jordan (forming Reduced Row Echelon Form), continuing the previous (row echelon) manipulation.

In [50]:
aug[0]=aug[0]-1*aug[2]                         # >>  R1 = R1-1R3
aug

array([[ 1,  1,  0,  3],
       [ 0,  1, -1, -2],
       [ 0,  0,  1,  3]])

In [51]:
aug[1]=aug[1]+1*aug[2]                         # >>  R2 = R2+1R3
aug

array([[1, 1, 0, 3],
       [0, 1, 0, 1],
       [0, 0, 1, 3]])

In [52]:
aug[0]=aug[0]-1*aug[1]                         # >>  R1 = R1-1R2
aug

array([[1, 0, 0, 2],
       [0, 1, 0, 1],
       [0, 0, 1, 3]])

# Now it is clear that both values are the same.
# x=2 , y=1 , z=3 (Reduced Row echelon form values)